### ISSUE TITLE
Question about the generated heatmaps

### ISSUE THREAD

**Issue by fmx789** [thuxyz19/Learnable-Sampling#1]
Hi, once more thanks for your fantastic work!
I attempted to reproduce your work for 20-30 epochs, howerver the heatmaps are not as representative as those in the paper (especially the last column). Is this normal? In addition, I wonder whether you provide training logs for reference? 
Thanks again!

![image](https://user-images.githubusercontent.com/33594261/210728959-8308b97f-59eb-4e82-ae8b-6e4ae28383fb.png)

**Comment by thuxyz19** [comment]
Thanks for your attention. I also observed similar patterns when training is not very sufficient. In my experience, a two-stage training is needed to obtain heatmaps of high quality. We first train the model using the combination of Human3.6M, COCO and MPI-INF-3DHP datasets and then finetune the model on 3DPW only.

**Comment by fmx789** [comment]
Thanks, I got it.

**Comment by fmx789** [comment]
One more question, are these 24 heat maps representing the same joints in the SMPL order?

**Comment by thuxyz19** [comment]
Yes, the 24 heat maps follow the same order of the SMPL joints.

**Comment by fmx789** [comment]
Thanks a lot. Would you mind share your MPI-INF-3DHP tsv files?
